CXX=clang++
CXXFLAGS=-std=c++14 -g 

CC=clang
CFLAGS=-std=c99 -g 

# If you're using clang, these are good flags to try
OPTFLAGS=-Ofast -march=native

# Add this flag to determine whether the compiler was able to vectorize
ANALYSIS=-Rpass-analysis=loop-vectorize

CXXFLAGS+=$(OPTFLAGS) $(ANALYSIS)
CFLAGS+=$(OPTFLAGS) $(ANALYSIS)
PYTHON=python

LUA_CFLAGS=-I/usr/local/include
LUA_LIBS=-L/usr/local/lib -llua
